// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpSuiteRevision = `-- name: BumpSuiteRevision :one
UPDATE suites
SET revision = revision + 1,
    current_version_id = COALESCE($1::text, current_version_id)
WHERE project_id = $2 AND suite_id = $3
RETURNING revision
`

type BumpSuiteRevisionParams struct {
	CurrentVersionID pgtype.Text
	ProjectID        string
	SuiteID          string
}

// Advances the revision by exactly one, optionally moving the current version,
// and returns the new revision.
func (q *Queries) BumpSuiteRevision(ctx context.Context, arg BumpSuiteRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpSuiteRevision, arg.CurrentVersionID, arg.ProjectID, arg.SuiteID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT project_id, suite_id, proposal_id, revision_id, source, evidence_emitter, evidence_source, evidence_revision_id, outcome FROM assessments
WHERE project_id = $1 AND suite_id = $2 AND proposal_id = $3
  AND revision_id = $4 AND source = $5
`

type GetAssessmentParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	RevisionID string
	Source     string
}

func (q *Queries) GetAssessment(ctx context.Context, arg GetAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessment,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
		arg.Source,
	)
	var i Assessment
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.ProposalID,
		&i.RevisionID,
		&i.Source,
		&i.EvidenceEmitter,
		&i.EvidenceSource,
		&i.EvidenceRevisionID,
		&i.Outcome,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT operation_id, project_id, suite_id, kind, source_command_id, receipt FROM operations WHERE operation_id = $1
`

func (q *Queries) GetOperation(ctx context.Context, operationID string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, operationID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.ProjectID,
		&i.SuiteID,
		&i.Kind,
		&i.SourceCommandID,
		&i.Receipt,
	)
	return i, err
}

const getOperationBySource = `-- name: GetOperationBySource :one
SELECT operation.operation_id, operation.project_id, operation.suite_id, operation.kind, operation.source_command_id, operation.receipt FROM operations AS operation
JOIN consent_results AS result ON result.operation_id = operation.operation_id
WHERE result.source_command_id = $1
`

// The original operation that processed a source command, not a later alias.
func (q *Queries) GetOperationBySource(ctx context.Context, sourceCommandID string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationBySource, sourceCommandID)
	var i Operation
	err := row.Scan(
		&i.OperationID,
		&i.ProjectID,
		&i.SuiteID,
		&i.Kind,
		&i.SourceCommandID,
		&i.Receipt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT project_id, revision_id, owner_id, owner_kind FROM policies
WHERE project_id = $1 AND revision_id = $2
`

type GetPolicyParams struct {
	ProjectID  string
	RevisionID string
}

func (q *Queries) GetPolicy(ctx context.Context, arg GetPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicy, arg.ProjectID, arg.RevisionID)
	var i Policy
	err := row.Scan(
		&i.ProjectID,
		&i.RevisionID,
		&i.OwnerID,
		&i.OwnerKind,
	)
	return i, err
}

const getPromotionByReference = `-- name: GetPromotionByReference :one
SELECT promotions.operation_id, promotions.project_id, promotions.suite_id, promotions.version_id, promotions.proposal_id, promotions.revision_id, promotions.carrier_id, promotions.source_revision, promotions.target_id, promotions.recorded_at, promotions.corrects_version_id, proposal_revisions.project_id, proposal_revisions.suite_id, proposal_revisions.proposal_id, proposal_revisions.revision_id, proposal_revisions.seq, proposal_revisions.origin, proposal_revisions.carrier_id, proposal_revisions.manifest_digest, proposal_revisions.scope_digest, proposal_revisions.covered_inputs, proposal_revisions.expected_version_id, proposal_revisions.policy_revision_id
FROM promotions
JOIN proposal_revisions ON proposal_revisions.project_id = promotions.project_id
    AND proposal_revisions.suite_id = promotions.suite_id
    AND proposal_revisions.proposal_id = promotions.proposal_id
    AND proposal_revisions.revision_id = promotions.revision_id
WHERE promotions.project_id = $1 AND promotions.suite_id = $2
  AND promotions.proposal_id = $3 AND promotions.revision_id = $4
`

type GetPromotionByReferenceParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	RevisionID string
}

type GetPromotionByReferenceRow struct {
	Promotion        Promotion
	ProposalRevision ProposalRevision
}

func (q *Queries) GetPromotionByReference(ctx context.Context, arg GetPromotionByReferenceParams) (GetPromotionByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPromotionByReference,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
	)
	var i GetPromotionByReferenceRow
	err := row.Scan(
		&i.Promotion.OperationID,
		&i.Promotion.ProjectID,
		&i.Promotion.SuiteID,
		&i.Promotion.VersionID,
		&i.Promotion.ProposalID,
		&i.Promotion.RevisionID,
		&i.Promotion.CarrierID,
		&i.Promotion.SourceRevision,
		&i.Promotion.TargetID,
		&i.Promotion.RecordedAt,
		&i.Promotion.CorrectsVersionID,
		&i.ProposalRevision.ProjectID,
		&i.ProposalRevision.SuiteID,
		&i.ProposalRevision.ProposalID,
		&i.ProposalRevision.RevisionID,
		&i.ProposalRevision.Seq,
		&i.ProposalRevision.Origin,
		&i.ProposalRevision.CarrierID,
		&i.ProposalRevision.ManifestDigest,
		&i.ProposalRevision.ScopeDigest,
		&i.ProposalRevision.CoveredInputs,
		&i.ProposalRevision.ExpectedVersionID,
		&i.ProposalRevision.PolicyRevisionID,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT project_id, suite_id, proposal_id, carrier_id FROM proposals
WHERE project_id = $1 AND suite_id = $2 AND proposal_id = $3
`

type GetProposalParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
}

func (q *Queries) GetProposal(ctx context.Context, arg GetProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposal, arg.ProjectID, arg.SuiteID, arg.ProposalID)
	var i Proposal
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.ProposalID,
		&i.CarrierID,
	)
	return i, err
}

const getProposalRevision = `-- name: GetProposalRevision :one
SELECT project_id, suite_id, proposal_id, revision_id, seq, origin, carrier_id, manifest_digest, scope_digest, covered_inputs, expected_version_id, policy_revision_id FROM proposal_revisions
WHERE project_id = $1 AND suite_id = $2 AND proposal_id = $3
  AND revision_id = $4
`

type GetProposalRevisionParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	RevisionID string
}

func (q *Queries) GetProposalRevision(ctx context.Context, arg GetProposalRevisionParams) (ProposalRevision, error) {
	row := q.db.QueryRow(ctx, getProposalRevision,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
	)
	var i ProposalRevision
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.ProposalID,
		&i.RevisionID,
		&i.Seq,
		&i.Origin,
		&i.CarrierID,
		&i.ManifestDigest,
		&i.ScopeDigest,
		&i.CoveredInputs,
		&i.ExpectedVersionID,
		&i.PolicyRevisionID,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT schema_version()::bigint AS version
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getVersion = `-- name: GetVersion :one
SELECT suite_versions.project_id, suite_versions.suite_id, suite_versions.version_id, suite_versions.manifest_digest, suite_versions.manifest, promotions.operation_id, promotions.project_id, promotions.suite_id, promotions.version_id, promotions.proposal_id, promotions.revision_id, promotions.carrier_id, promotions.source_revision, promotions.target_id, promotions.recorded_at, promotions.corrects_version_id, proposal_revisions.project_id, proposal_revisions.suite_id, proposal_revisions.proposal_id, proposal_revisions.revision_id, proposal_revisions.seq, proposal_revisions.origin, proposal_revisions.carrier_id, proposal_revisions.manifest_digest, proposal_revisions.scope_digest, proposal_revisions.covered_inputs, proposal_revisions.expected_version_id, proposal_revisions.policy_revision_id
FROM suite_versions
JOIN promotions ON promotions.project_id = suite_versions.project_id
    AND promotions.suite_id = suite_versions.suite_id
    AND promotions.version_id = suite_versions.version_id
JOIN proposal_revisions ON proposal_revisions.project_id = promotions.project_id
    AND proposal_revisions.suite_id = promotions.suite_id
    AND proposal_revisions.proposal_id = promotions.proposal_id
    AND proposal_revisions.revision_id = promotions.revision_id
WHERE suite_versions.project_id = $1 AND suite_versions.suite_id = $2
  AND suite_versions.version_id = $3
`

type GetVersionParams struct {
	ProjectID string
	SuiteID   string
	VersionID string
}

type GetVersionRow struct {
	SuiteVersion     SuiteVersion
	Promotion        Promotion
	ProposalRevision ProposalRevision
}

// A version with the promotion that created it and the proposal revision that
// holds the approval binding.
func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (GetVersionRow, error) {
	row := q.db.QueryRow(ctx, getVersion, arg.ProjectID, arg.SuiteID, arg.VersionID)
	var i GetVersionRow
	err := row.Scan(
		&i.SuiteVersion.ProjectID,
		&i.SuiteVersion.SuiteID,
		&i.SuiteVersion.VersionID,
		&i.SuiteVersion.ManifestDigest,
		&i.SuiteVersion.Manifest,
		&i.Promotion.OperationID,
		&i.Promotion.ProjectID,
		&i.Promotion.SuiteID,
		&i.Promotion.VersionID,
		&i.Promotion.ProposalID,
		&i.Promotion.RevisionID,
		&i.Promotion.CarrierID,
		&i.Promotion.SourceRevision,
		&i.Promotion.TargetID,
		&i.Promotion.RecordedAt,
		&i.Promotion.CorrectsVersionID,
		&i.ProposalRevision.ProjectID,
		&i.ProposalRevision.SuiteID,
		&i.ProposalRevision.ProposalID,
		&i.ProposalRevision.RevisionID,
		&i.ProposalRevision.Seq,
		&i.ProposalRevision.Origin,
		&i.ProposalRevision.CarrierID,
		&i.ProposalRevision.ManifestDigest,
		&i.ProposalRevision.ScopeDigest,
		&i.ProposalRevision.CoveredInputs,
		&i.ProposalRevision.ExpectedVersionID,
		&i.ProposalRevision.PolicyRevisionID,
	)
	return i, err
}

const insertAssessment = `-- name: InsertAssessment :exec
INSERT INTO assessments (project_id, suite_id, proposal_id, revision_id, source, evidence_emitter, evidence_source, evidence_revision_id, outcome)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9)
`

type InsertAssessmentParams struct {
	ProjectID          string
	SuiteID            string
	ProposalID         string
	RevisionID         string
	Source             string
	EvidenceEmitter    pgtype.Text
	EvidenceSource     pgtype.Text
	EvidenceRevisionID pgtype.Text
	Outcome            pgtype.Text
}

func (q *Queries) InsertAssessment(ctx context.Context, arg InsertAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertAssessment,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
		arg.Source,
		arg.EvidenceEmitter,
		arg.EvidenceSource,
		arg.EvidenceRevisionID,
		arg.Outcome,
	)
	return err
}

const insertConsentResult = `-- name: InsertConsentResult :exec
INSERT INTO consent_results (source_command_id, operation_id, project_id, suite_id, proposal_id, revision_id,
    actor_id, actor_kind, carrier_id, action, command_order, outcome, reason)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13)
`

type InsertConsentResultParams struct {
	SourceCommandID string
	OperationID     string
	ProjectID       string
	SuiteID         string
	ProposalID      string
	RevisionID      string
	ActorID         string
	ActorKind       string
	CarrierID       string
	Action          string
	CommandOrder    int64
	Outcome         string
	Reason          string
}

func (q *Queries) InsertConsentResult(ctx context.Context, arg InsertConsentResultParams) error {
	_, err := q.db.Exec(ctx, insertConsentResult,
		arg.SourceCommandID,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
		arg.ActorID,
		arg.ActorKind,
		arg.CarrierID,
		arg.Action,
		arg.CommandOrder,
		arg.Outcome,
		arg.Reason,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO operations (operation_id, project_id, suite_id, kind, source_command_id, receipt)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOperationParams struct {
	OperationID     string
	ProjectID       string
	SuiteID         string
	Kind            string
	SourceCommandID pgtype.Text
	Receipt         []byte
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.Kind,
		arg.SourceCommandID,
		arg.Receipt,
	)
	return err
}

const insertPolicy = `-- name: InsertPolicy :exec
INSERT INTO policies (project_id, revision_id, owner_id, owner_kind)
VALUES ($1, $2, $3, $4)
`

type InsertPolicyParams struct {
	ProjectID  string
	RevisionID string
	OwnerID    string
	OwnerKind  string
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) error {
	_, err := q.db.Exec(ctx, insertPolicy,
		arg.ProjectID,
		arg.RevisionID,
		arg.OwnerID,
		arg.OwnerKind,
	)
	return err
}

const insertPromotion = `-- name: InsertPromotion :exec
INSERT INTO promotions (operation_id, project_id, suite_id, version_id, proposal_id, revision_id, carrier_id,
    source_revision, target_id, recorded_at, corrects_version_id)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11)
`

type InsertPromotionParams struct {
	OperationID       string
	ProjectID         string
	SuiteID           string
	VersionID         string
	ProposalID        string
	RevisionID        string
	CarrierID         string
	SourceRevision    string
	TargetID          string
	RecordedAt        pgtype.Timestamptz
	CorrectsVersionID pgtype.Text
}

func (q *Queries) InsertPromotion(ctx context.Context, arg InsertPromotionParams) error {
	_, err := q.db.Exec(ctx, insertPromotion,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.VersionID,
		arg.ProposalID,
		arg.RevisionID,
		arg.CarrierID,
		arg.SourceRevision,
		arg.TargetID,
		arg.RecordedAt,
		arg.CorrectsVersionID,
	)
	return err
}

const insertProposal = `-- name: InsertProposal :exec
INSERT INTO proposals (project_id, suite_id, proposal_id, carrier_id)
VALUES ($1, $2, $3, $4)
`

type InsertProposalParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	CarrierID  string
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) error {
	_, err := q.db.Exec(ctx, insertProposal,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.CarrierID,
	)
	return err
}

const insertProposalRevision = `-- name: InsertProposalRevision :exec
INSERT INTO proposal_revisions (project_id, suite_id, proposal_id, revision_id, seq, origin, carrier_id,
    manifest_digest, scope_digest, covered_inputs, expected_version_id, policy_revision_id)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12)
`

type InsertProposalRevisionParams struct {
	ProjectID         string
	SuiteID           string
	ProposalID        string
	RevisionID        string
	Seq               int64
	Origin            string
	CarrierID         string
	ManifestDigest    string
	ScopeDigest       string
	CoveredInputs     []byte
	ExpectedVersionID pgtype.Text
	PolicyRevisionID  string
}

func (q *Queries) InsertProposalRevision(ctx context.Context, arg InsertProposalRevisionParams) error {
	_, err := q.db.Exec(ctx, insertProposalRevision,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.RevisionID,
		arg.Seq,
		arg.Origin,
		arg.CarrierID,
		arg.ManifestDigest,
		arg.ScopeDigest,
		arg.CoveredInputs,
		arg.ExpectedVersionID,
		arg.PolicyRevisionID,
	)
	return err
}

const insertSuite = `-- name: InsertSuite :exec
INSERT INTO suites (project_id, suite_id, revision, current_version_id, target_id, policy_revision_id)
VALUES ($1, $2, $3, $4, $5,
    $6)
`

type InsertSuiteParams struct {
	ProjectID        string
	SuiteID          string
	Revision         int64
	CurrentVersionID pgtype.Text
	TargetID         string
	PolicyRevisionID string
}

func (q *Queries) InsertSuite(ctx context.Context, arg InsertSuiteParams) error {
	_, err := q.db.Exec(ctx, insertSuite,
		arg.ProjectID,
		arg.SuiteID,
		arg.Revision,
		arg.CurrentVersionID,
		arg.TargetID,
		arg.PolicyRevisionID,
	)
	return err
}

const insertSuiteVersion = `-- name: InsertSuiteVersion :exec
INSERT INTO suite_versions (project_id, suite_id, version_id, manifest_digest, manifest)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSuiteVersionParams struct {
	ProjectID      string
	SuiteID        string
	VersionID      string
	ManifestDigest string
	Manifest       []byte
}

func (q *Queries) InsertSuiteVersion(ctx context.Context, arg InsertSuiteVersionParams) error {
	_, err := q.db.Exec(ctx, insertSuiteVersion,
		arg.ProjectID,
		arg.SuiteID,
		arg.VersionID,
		arg.ManifestDigest,
		arg.Manifest,
	)
	return err
}

const listConsentAliases = `-- name: ListConsentAliases :many
SELECT operation.operation_id, operation.source_command_id::text AS source_command_id
FROM operations AS operation
JOIN consent_results AS result ON result.project_id = operation.project_id
    AND result.suite_id = operation.suite_id
    AND result.source_command_id = operation.source_command_id
WHERE result.project_id = $1 AND result.suite_id = $2 AND result.proposal_id = $3
  AND operation.operation_id <> result.operation_id
ORDER BY operation.operation_id
`

type ListConsentAliasesParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
}

type ListConsentAliasesRow struct {
	OperationID     string
	SourceCommandID string
}

// Operation ids that replayed an already processed source command of the proposal.
func (q *Queries) ListConsentAliases(ctx context.Context, arg ListConsentAliasesParams) ([]ListConsentAliasesRow, error) {
	rows, err := q.db.Query(ctx, listConsentAliases, arg.ProjectID, arg.SuiteID, arg.ProposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsentAliasesRow{}
	for rows.Next() {
		var i ListConsentAliasesRow
		if err := rows.Scan(&i.OperationID, &i.SourceCommandID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentResults = `-- name: ListConsentResults :many
SELECT source_command_id, operation_id, project_id, suite_id, proposal_id, revision_id, actor_id, actor_kind, carrier_id, action, command_order, outcome, reason, seq FROM consent_results
WHERE project_id = $1 AND suite_id = $2 AND proposal_id = $3
ORDER BY seq
`

type ListConsentResultsParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
}

func (q *Queries) ListConsentResults(ctx context.Context, arg ListConsentResultsParams) ([]ConsentResult, error) {
	rows, err := q.db.Query(ctx, listConsentResults, arg.ProjectID, arg.SuiteID, arg.ProposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentResult{}
	for rows.Next() {
		var i ConsentResult
		if err := rows.Scan(
			&i.SourceCommandID,
			&i.OperationID,
			&i.ProjectID,
			&i.SuiteID,
			&i.ProposalID,
			&i.RevisionID,
			&i.ActorID,
			&i.ActorKind,
			&i.CarrierID,
			&i.Action,
			&i.CommandOrder,
			&i.Outcome,
			&i.Reason,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalRevisions = `-- name: ListProposalRevisions :many
SELECT project_id, suite_id, proposal_id, revision_id, seq, origin, carrier_id, manifest_digest, scope_digest, covered_inputs, expected_version_id, policy_revision_id FROM proposal_revisions
WHERE project_id = $1 AND suite_id = $2 AND proposal_id = $3
ORDER BY seq
`

type ListProposalRevisionsParams struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
}

func (q *Queries) ListProposalRevisions(ctx context.Context, arg ListProposalRevisionsParams) ([]ProposalRevision, error) {
	rows, err := q.db.Query(ctx, listProposalRevisions, arg.ProjectID, arg.SuiteID, arg.ProposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProposalRevision{}
	for rows.Next() {
		var i ProposalRevision
		if err := rows.Scan(
			&i.ProjectID,
			&i.SuiteID,
			&i.ProposalID,
			&i.RevisionID,
			&i.Seq,
			&i.Origin,
			&i.CarrierID,
			&i.ManifestDigest,
			&i.ScopeDigest,
			&i.CoveredInputs,
			&i.ExpectedVersionID,
			&i.PolicyRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSuite = `-- name: LockSuite :one
SELECT project_id, suite_id, revision, current_version_id, target_id, policy_revision_id FROM suites
WHERE project_id = $1 AND suite_id = $2
FOR UPDATE
`

type LockSuiteParams struct {
	ProjectID string
	SuiteID   string
}

func (q *Queries) LockSuite(ctx context.Context, arg LockSuiteParams) (Suite, error) {
	row := q.db.QueryRow(ctx, lockSuite, arg.ProjectID, arg.SuiteID)
	var i Suite
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.Revision,
		&i.CurrentVersionID,
		&i.TargetID,
		&i.PolicyRevisionID,
	)
	return i, err
}
