// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Assessment struct {
	ProjectID          string
	SuiteID            string
	ProposalID         string
	RevisionID         string
	Source             string
	EvidenceEmitter    pgtype.Text
	EvidenceSource     pgtype.Text
	EvidenceRevisionID pgtype.Text
	Outcome            pgtype.Text
}

type ConsentResult struct {
	SourceCommandID string
	OperationID     string
	ProjectID       string
	SuiteID         string
	ProposalID      string
	RevisionID      string
	ActorID         string
	ActorKind       string
	CarrierID       string
	Action          string
	CommandOrder    int64
	Outcome         string
	Reason          string
	Seq             int64
}

type Operation struct {
	OperationID     string
	ProjectID       string
	SuiteID         string
	Kind            string
	SourceCommandID pgtype.Text
	Receipt         []byte
}

type Outbox struct {
	Key           string
	ProjectID     pgtype.Text
	SuiteID       pgtype.Text
	Kind          string
	Payload       []byte
	State         string
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type Policy struct {
	ProjectID  string
	RevisionID string
	OwnerID    string
	OwnerKind  string
}

type Promotion struct {
	OperationID       string
	ProjectID         string
	SuiteID           string
	VersionID         string
	ProposalID        string
	RevisionID        string
	CarrierID         string
	SourceRevision    string
	TargetID          string
	RecordedAt        pgtype.Timestamptz
	CorrectsVersionID pgtype.Text
}

type Proposal struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	CarrierID  string
}

type ProposalRevision struct {
	ProjectID         string
	SuiteID           string
	ProposalID        string
	RevisionID        string
	Seq               int64
	Origin            string
	CarrierID         string
	ManifestDigest    string
	ScopeDigest       string
	CoveredInputs     []byte
	ExpectedVersionID pgtype.Text
	PolicyRevisionID  string
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  pgtype.Timestamptz
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Version   int64
}

type RiverNotification struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Suite struct {
	ProjectID        string
	SuiteID          string
	Revision         int64
	CurrentVersionID pgtype.Text
	TargetID         string
	PolicyRevisionID string
}

type SuiteVersion struct {
	ProjectID      string
	SuiteID        string
	VersionID      string
	ManifestDigest string
	Manifest       []byte
}
