// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ProjectID          string
	SuiteID            string
	ProposalID         string
	RevisionID         string
	Source             string
	EvidenceEmitter    pgtype.Text
	EvidenceSource     pgtype.Text
	EvidenceRevisionID pgtype.Text
	Outcome            pgtype.Text
}

type ConsentResult struct {
	SourceCommandID string
	OperationID     string
	ProjectID       string
	SuiteID         string
	ProposalID      string
	RevisionID      string
	ActorID         string
	ActorKind       string
	CarrierID       string
	Action          string
	CommandOrder    int64
	Outcome         string
	Reason          string
	Seq             int64
}

type Operation struct {
	OperationID     string
	ProjectID       string
	SuiteID         string
	Kind            string
	SourceCommandID pgtype.Text
	Receipt         []byte
}

type Policy struct {
	ProjectID  string
	RevisionID string
	OwnerID    string
	OwnerKind  string
}

type Promotion struct {
	OperationID       string
	ProjectID         string
	SuiteID           string
	VersionID         string
	ProposalID        string
	RevisionID        string
	CarrierID         string
	SourceRevision    string
	TargetID          string
	RecordedAt        pgtype.Timestamptz
	CorrectsVersionID pgtype.Text
}

type Proposal struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	CarrierID  string
}

type ProposalRevision struct {
	ProjectID         string
	SuiteID           string
	ProposalID        string
	RevisionID        string
	Seq               int64
	Origin            string
	CarrierID         string
	ManifestDigest    string
	ScopeDigest       string
	CoveredInputs     []byte
	ExpectedVersionID pgtype.Text
	PolicyRevisionID  string
}

type ScheduleEntry struct {
	ProjectID  string
	SuiteID    string
	ProposalID string
	CarrierID  string
	Position   int64
	State      string
}

type Suite struct {
	ProjectID          string
	SuiteID            string
	Revision           int64
	CurrentVersionID   pgtype.Text
	TargetID           string
	PolicyRevisionID   string
	ScheduleGeneration int64
}

type SuiteVersion struct {
	ProjectID      string
	SuiteID        string
	VersionID      string
	ManifestDigest string
	Manifest       []byte
}
