// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	OperationID  string
	ProjectID    string
	SuiteID      string
	EventKind    int16
	EventPayload []byte
}

type ConsentAcknowledgment struct {
	OperationID           string
	ProjectID             string
	SuiteID               string
	Kind                  int16
	AcknowledgmentPayload []byte
}

type ConsentSource struct {
	SourceCommandID string
	ProjectID       string
	SuiteID         string
	OperationID     string
	Kind            int16
}

type OperationReceipt struct {
	OperationID    string
	ProjectID      string
	SuiteID        string
	Kind           int16
	ReceiptPayload []byte
}

type Promotion struct {
	OperationID        string
	ProjectID          string
	SuiteID            string
	OperationKind      int16
	VersionID          string
	ProposalID         string
	ProposalRevisionID string
	ExpectedVersionID  pgtype.Text
	CorrectsVersionID  pgtype.Text
	CarrierID          string
	SourceRevision     string
	TargetID           string
	RecordedAt         pgtype.Timestamptz
	PromotionPayload   []byte
}

type PublicationIntent struct {
	OperationID        string
	ProjectID          string
	SuiteID            string
	PublicationPayload []byte
}

type Suite struct {
	ProjectID         string
	SuiteID           string
	CurrentVersionID  pgtype.Text
	AuthorityRevision pgtype.Numeric
	GovernancePayload []byte
}

type SuiteVersion struct {
	ProjectID      string
	SuiteID        string
	VersionID      string
	ManifestDigest string
	VersionPayload []byte
}
