// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persistence.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cASAuthority = `-- name: CASAuthority :execrows
UPDATE suites
SET authority_revision = $1::text::numeric,
    current_version_id = $2::text,
    governance_payload = $3
WHERE project_id = $4 AND suite_id = $5
  AND authority_revision = $6::text::numeric
  AND current_version_id IS NOT DISTINCT FROM $7::text
`

type CASAuthorityParams struct {
	NewRevision       string
	NewCurrent        pgtype.Text
	GovernancePayload []byte
	ProjectID         string
	SuiteID           string
	ExpectedRevision  string
	ExpectedCurrent   pgtype.Text
}

func (q *Queries) CASAuthority(ctx context.Context, arg CASAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, cASAuthority,
		arg.NewRevision,
		arg.NewCurrent,
		arg.GovernancePayload,
		arg.ProjectID,
		arg.SuiteID,
		arg.ExpectedRevision,
		arg.ExpectedCurrent,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findConsentSource = `-- name: FindConsentSource :one
SELECT receipt.operation_id, receipt.project_id, receipt.suite_id, receipt.kind, receipt.receipt_payload FROM consent_sources AS source
JOIN operation_receipts AS receipt ON receipt.operation_id = source.operation_id
WHERE source.source_command_id = $1
`

func (q *Queries) FindConsentSource(ctx context.Context, sourceCommandID string) (OperationReceipt, error) {
	row := q.db.QueryRow(ctx, findConsentSource, sourceCommandID)
	var i OperationReceipt
	err := row.Scan(
		&i.OperationID,
		&i.ProjectID,
		&i.SuiteID,
		&i.Kind,
		&i.ReceiptPayload,
	)
	return i, err
}

const findOperation = `-- name: FindOperation :one
SELECT operation_id, project_id, suite_id, kind, receipt_payload FROM operation_receipts WHERE operation_id = $1
`

func (q *Queries) FindOperation(ctx context.Context, operationID string) (OperationReceipt, error) {
	row := q.db.QueryRow(ctx, findOperation, operationID)
	var i OperationReceipt
	err := row.Scan(
		&i.OperationID,
		&i.ProjectID,
		&i.SuiteID,
		&i.Kind,
		&i.ReceiptPayload,
	)
	return i, err
}

const findPromotionByReference = `-- name: FindPromotionByReference :one
SELECT operation_id, project_id, suite_id, operation_kind, version_id, proposal_id, proposal_revision_id, expected_version_id, corrects_version_id, carrier_id, source_revision, target_id, recorded_at, promotion_payload FROM promotions
WHERE project_id = $1 AND suite_id = $2
  AND proposal_id = $3 AND proposal_revision_id = $4
`

type FindPromotionByReferenceParams struct {
	ProjectID          string
	SuiteID            string
	ProposalID         string
	ProposalRevisionID string
}

func (q *Queries) FindPromotionByReference(ctx context.Context, arg FindPromotionByReferenceParams) (Promotion, error) {
	row := q.db.QueryRow(ctx, findPromotionByReference,
		arg.ProjectID,
		arg.SuiteID,
		arg.ProposalID,
		arg.ProposalRevisionID,
	)
	var i Promotion
	err := row.Scan(
		&i.OperationID,
		&i.ProjectID,
		&i.SuiteID,
		&i.OperationKind,
		&i.VersionID,
		&i.ProposalID,
		&i.ProposalRevisionID,
		&i.ExpectedVersionID,
		&i.CorrectsVersionID,
		&i.CarrierID,
		&i.SourceRevision,
		&i.TargetID,
		&i.RecordedAt,
		&i.PromotionPayload,
	)
	return i, err
}

const getAuthority = `-- name: GetAuthority :one
SELECT project_id, suite_id, current_version_id, authority_revision::text AS authority_revision, governance_payload
FROM suites WHERE project_id = $1 AND suite_id = $2
`

type GetAuthorityParams struct {
	ProjectID string
	SuiteID   string
}

type GetAuthorityRow struct {
	ProjectID         string
	SuiteID           string
	CurrentVersionID  pgtype.Text
	AuthorityRevision string
	GovernancePayload []byte
}

func (q *Queries) GetAuthority(ctx context.Context, arg GetAuthorityParams) (GetAuthorityRow, error) {
	row := q.db.QueryRow(ctx, getAuthority, arg.ProjectID, arg.SuiteID)
	var i GetAuthorityRow
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.CurrentVersionID,
		&i.AuthorityRevision,
		&i.GovernancePayload,
	)
	return i, err
}

const getVersion = `-- name: GetVersion :one
SELECT project_id, suite_id, version_id, manifest_digest, version_payload FROM suite_versions
WHERE project_id = $1 AND suite_id = $2 AND version_id = $3
`

type GetVersionParams struct {
	ProjectID string
	SuiteID   string
	VersionID string
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (SuiteVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, arg.ProjectID, arg.SuiteID, arg.VersionID)
	var i SuiteVersion
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.VersionID,
		&i.ManifestDigest,
		&i.VersionPayload,
	)
	return i, err
}

const insertAcknowledgment = `-- name: InsertAcknowledgment :exec
INSERT INTO consent_acknowledgments (operation_id, project_id, suite_id, acknowledgment_payload)
VALUES ($1, $2, $3, $4)
`

type InsertAcknowledgmentParams struct {
	OperationID           string
	ProjectID             string
	SuiteID               string
	AcknowledgmentPayload []byte
}

func (q *Queries) InsertAcknowledgment(ctx context.Context, arg InsertAcknowledgmentParams) error {
	_, err := q.db.Exec(ctx, insertAcknowledgment,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.AcknowledgmentPayload,
	)
	return err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_events (operation_id, project_id, suite_id, event_kind, event_payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditParams struct {
	OperationID  string
	ProjectID    string
	SuiteID      string
	EventKind    int16
	EventPayload []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.EventKind,
		arg.EventPayload,
	)
	return err
}

const insertConsentSource = `-- name: InsertConsentSource :exec
INSERT INTO consent_sources (source_command_id, project_id, suite_id, operation_id)
VALUES ($1, $2, $3, $4)
`

type InsertConsentSourceParams struct {
	SourceCommandID string
	ProjectID       string
	SuiteID         string
	OperationID     string
}

func (q *Queries) InsertConsentSource(ctx context.Context, arg InsertConsentSourceParams) error {
	_, err := q.db.Exec(ctx, insertConsentSource,
		arg.SourceCommandID,
		arg.ProjectID,
		arg.SuiteID,
		arg.OperationID,
	)
	return err
}

const insertInitialAuthority = `-- name: InsertInitialAuthority :exec
INSERT INTO suites (project_id, suite_id, authority_revision, governance_payload)
VALUES ($1, $2, $3::text::numeric, $4)
`

type InsertInitialAuthorityParams struct {
	ProjectID         string
	SuiteID           string
	AuthorityRevision string
	GovernancePayload []byte
}

func (q *Queries) InsertInitialAuthority(ctx context.Context, arg InsertInitialAuthorityParams) error {
	_, err := q.db.Exec(ctx, insertInitialAuthority,
		arg.ProjectID,
		arg.SuiteID,
		arg.AuthorityRevision,
		arg.GovernancePayload,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO operation_receipts (operation_id, project_id, suite_id, kind, receipt_payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOperationParams struct {
	OperationID    string
	ProjectID      string
	SuiteID        string
	Kind           int16
	ReceiptPayload []byte
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.Kind,
		arg.ReceiptPayload,
	)
	return err
}

const insertPromotion = `-- name: InsertPromotion :exec
INSERT INTO promotions (operation_id, project_id, suite_id, operation_kind, version_id, proposal_id, proposal_revision_id,
    expected_version_id, corrects_version_id, carrier_id, source_revision, target_id, recorded_at, promotion_payload)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14)
`

type InsertPromotionParams struct {
	OperationID        string
	ProjectID          string
	SuiteID            string
	OperationKind      int16
	VersionID          string
	ProposalID         string
	ProposalRevisionID string
	ExpectedVersionID  pgtype.Text
	CorrectsVersionID  pgtype.Text
	CarrierID          string
	SourceRevision     string
	TargetID           string
	RecordedAt         pgtype.Timestamptz
	PromotionPayload   []byte
}

func (q *Queries) InsertPromotion(ctx context.Context, arg InsertPromotionParams) error {
	_, err := q.db.Exec(ctx, insertPromotion,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.OperationKind,
		arg.VersionID,
		arg.ProposalID,
		arg.ProposalRevisionID,
		arg.ExpectedVersionID,
		arg.CorrectsVersionID,
		arg.CarrierID,
		arg.SourceRevision,
		arg.TargetID,
		arg.RecordedAt,
		arg.PromotionPayload,
	)
	return err
}

const insertPublication = `-- name: InsertPublication :exec
INSERT INTO publication_intents (operation_id, project_id, suite_id, publication_payload)
VALUES ($1, $2, $3, $4)
`

type InsertPublicationParams struct {
	OperationID        string
	ProjectID          string
	SuiteID            string
	PublicationPayload []byte
}

func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) error {
	_, err := q.db.Exec(ctx, insertPublication,
		arg.OperationID,
		arg.ProjectID,
		arg.SuiteID,
		arg.PublicationPayload,
	)
	return err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO suite_versions (project_id, suite_id, version_id, manifest_digest, version_payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVersionParams struct {
	ProjectID      string
	SuiteID        string
	VersionID      string
	ManifestDigest string
	VersionPayload []byte
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.Exec(ctx, insertVersion,
		arg.ProjectID,
		arg.SuiteID,
		arg.VersionID,
		arg.ManifestDigest,
		arg.VersionPayload,
	)
	return err
}

const lockAuthority = `-- name: LockAuthority :one
SELECT project_id, suite_id, current_version_id, authority_revision::text AS authority_revision, governance_payload
FROM suites WHERE project_id = $1 AND suite_id = $2 FOR UPDATE
`

type LockAuthorityParams struct {
	ProjectID string
	SuiteID   string
}

type LockAuthorityRow struct {
	ProjectID         string
	SuiteID           string
	CurrentVersionID  pgtype.Text
	AuthorityRevision string
	GovernancePayload []byte
}

func (q *Queries) LockAuthority(ctx context.Context, arg LockAuthorityParams) (LockAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockAuthority, arg.ProjectID, arg.SuiteID)
	var i LockAuthorityRow
	err := row.Scan(
		&i.ProjectID,
		&i.SuiteID,
		&i.CurrentVersionID,
		&i.AuthorityRevision,
		&i.GovernancePayload,
	)
	return i, err
}
