// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutbox = `-- name: ClaimOutbox :many
WITH due AS (
    SELECT outbox.key FROM outbox
    WHERE state = 'pending'
      AND next_attempt_at <= $2::timestamptz
      AND attempts < $3::int
    ORDER BY next_attempt_at, outbox.key
    LIMIT $4::int
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox
SET attempts = outbox.attempts + 1,
    next_attempt_at = $1::timestamptz
FROM due
WHERE outbox.key = due.key
RETURNING outbox.key, outbox.kind, outbox.payload, outbox.attempts
`

type ClaimOutboxParams struct {
	LeaseUntil  pgtype.Timestamptz
	Now         pgtype.Timestamptz
	MaxAttempts int32
	Batch       int32
}

type ClaimOutboxRow struct {
	Key      string
	Kind     string
	Payload  []byte
	Attempts int32
}

// Claims due messages: counts the attempt and hides them until the lease expires.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox,
		arg.LeaseUntil,
		arg.Now,
		arg.MaxAttempts,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxRow{}
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.Key,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failExhaustedOutbox = `-- name: FailExhaustedOutbox :many
UPDATE outbox
SET state = 'failed',
    last_error = 'delivery abandoned: every attempt was claimed without an outcome',
    finished_at = $1::timestamptz
WHERE state = 'pending'
  AND next_attempt_at <= $1::timestamptz
  AND attempts >= $2::int
RETURNING key, kind
`

type FailExhaustedOutboxParams struct {
	Now         pgtype.Timestamptz
	MaxAttempts int32
}

type FailExhaustedOutboxRow struct {
	Key  string
	Kind string
}

// Pending messages that were claimed on every attempt without an outcome stop here.
func (q *Queries) FailExhaustedOutbox(ctx context.Context, arg FailExhaustedOutboxParams) ([]FailExhaustedOutboxRow, error) {
	rows, err := q.db.Query(ctx, failExhaustedOutbox, arg.Now, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailExhaustedOutboxRow{}
	for rows.Next() {
		var i FailExhaustedOutboxRow
		if err := rows.Scan(&i.Key, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishOutbox = `-- name: FinishOutbox :execrows
UPDATE outbox
SET state = $1,
    last_error = COALESCE($2, last_error),
    next_attempt_at = COALESCE($3, next_attempt_at),
    finished_at = $4
WHERE key = $5 AND state = 'pending' AND attempts = $6
`

type FinishOutboxParams struct {
	State         string
	LastError     pgtype.Text
	NextAttemptAt pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	Key           string
	Attempts      int32
}

// Records the outcome of a claim; updates nothing when the message was reclaimed since.
func (q *Queries) FinishOutbox(ctx context.Context, arg FinishOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishOutbox,
		arg.State,
		arg.LastError,
		arg.NextAttemptAt,
		arg.FinishedAt,
		arg.Key,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobState = `-- name: GetJobState :one
SELECT state::text AS state FROM river_job WHERE id = $1
`

func (q *Queries) GetJobState(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getJobState, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const getOutboxState = `-- name: GetOutboxState :one
SELECT state FROM outbox WHERE key = $1
`

func (q *Queries) GetOutboxState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getOutboxState, key)
	var state string
	err := row.Scan(&state)
	return state, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (key, project_id, suite_id, kind, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxParams struct {
	Key       string
	ProjectID pgtype.Text
	SuiteID   pgtype.Text
	Kind      string
	Payload   []byte
}

// project_id and suite_id are both set (a governance message) or both null (a system message).
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox,
		arg.Key,
		arg.ProjectID,
		arg.SuiteID,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const releaseOutbox = `-- name: ReleaseOutbox :execrows
UPDATE outbox
SET attempts = attempts - 1,
    next_attempt_at = $1::timestamptz
WHERE key = $2 AND state = 'pending' AND attempts = $3
`

type ReleaseOutboxParams struct {
	NextAttemptAt pgtype.Timestamptz
	Key           string
	Attempts      int32
}

// Gives back a claim that was never tried: restores the attempt and makes the message due.
func (q *Queries) ReleaseOutbox(ctx context.Context, arg ReleaseOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOutbox, arg.NextAttemptAt, arg.Key, arg.Attempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
