// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package dbgen

import (
	"context"
)

const countJobsByState = `-- name: CountJobsByState :many
SELECT state::text AS state, count(*) AS total
FROM river_job
WHERE kind <> 'outbox_relay'
GROUP BY state
`

type CountJobsByStateRow struct {
	State string
	Total int64
}

// The relay's periodic job (kind outbox_relay, owned by the River adapter) is the service's own bookkeeping, not work.
func (q *Queries) CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error) {
	rows, err := q.db.Query(ctx, countJobsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStateRow{}
	for rows.Next() {
		var i CountJobsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOutboxByState = `-- name: CountOutboxByState :many
SELECT state, count(*) AS total
FROM outbox
GROUP BY state
`

type CountOutboxByStateRow struct {
	State string
	Total int64
}

func (q *Queries) CountOutboxByState(ctx context.Context) ([]CountOutboxByStateRow, error) {
	rows, err := q.db.Query(ctx, countOutboxByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOutboxByStateRow{}
	for rows.Next() {
		var i CountOutboxByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
