#Requires -Version 7.2
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'check-persistence.ps1') -Mode Library
$checks=0
function Assert-PersistenceRejection {
    param([scriptblock]$Action, [string]$Scenario)
    $failed=$false
    try { & $Action | Out-Null } catch { $failed=$true }
    if (-not $failed) { throw "Generation freshness accepted $Scenario." }
}
$before=@{'models.go'=('a'*64);'governance.sql.go'=('b'*64)}
Assert-GeneratedQueriesCurrent -Before $before -After @{'models.go'=('a'*64);'governance.sql.go'=('b'*64)}
$checks++
Assert-PersistenceRejection { Assert-GeneratedQueriesCurrent -Before $before -After @{'models.go'=('a'*64);'governance.sql.go'=('c'*64)} } 'changed generated content'
$checks++
Assert-PersistenceRejection { Assert-GeneratedQueriesCurrent -Before $before -After @{'models.go'=('a'*64);'governance.sql.go'=('b'*64);'new.go'=('c'*64)} } 'an untracked generated output'
$checks++
Assert-PersistenceRejection { Assert-GeneratedQueriesCurrent -Before $before -After @{'models.go'=('a'*64)} } 'removed generated output'
$checks++
Assert-PersistenceRejection { Assert-GeneratedQueriesCurrent -Before @{} -After @{} } 'absent generated baseline'
$checks++
Assert-PersistenceRejection { Assert-GeneratedQueriesCurrent -Before @{'models.go'='invalid'} -After @{'models.go'='invalid'} } 'invalid digest inventory'
$checks++
$base=[IO.Path]::GetFullPath((Join-Path (Split-Path $PSScriptRoot -Parent) '.cache/persistence-tests'))
$fixture=Join-Path $base ([Guid]::NewGuid().ToString('N'))
$output=Join-Path $fixture 'internal/adapters/postgres/internal/dbgen'
New-Item -ItemType Directory -Path $output -Force | Out-Null
try {
    Set-Content -LiteralPath (Join-Path $fixture 'sqlc.yaml') -Value @('version: "2"','sql:','  - engine: "postgresql"','    schema: "internal/adapters/postgres/migrations"','    queries: "internal/adapters/postgres/queries"','    gen:','      go:','        package: "dbgen"','        out: "internal/adapters/postgres/internal/dbgen"','        sql_package: "pgx/v5"') -Encoding utf8NoBOM
    $original='package dbgen'
    Set-Content -LiteralPath (Join-Path $output 'models.go') -Value $original -Encoding utf8NoBOM
    $state=[pscustomobject]@{Calls=0}
    Invoke-GeneratedQueryVerification -Root $fixture -Generate {
        param($Config,$Destination)
        $state.Calls++
        $configText=Get-Content -LiteralPath $Config -Raw
        if(-not $configText.Contains($Destination.Replace('\','/'))){throw 'Staged configuration does not bind the actual private output directory.'}
        Set-Content -LiteralPath (Join-Path $Destination 'models.go') -Value $original -Encoding utf8NoBOM
    }
    if($state.Calls -ne 1){throw 'Generation verification did not invoke the actual generator.'}
    $checks++
    Assert-PersistenceRejection { Invoke-GeneratedQueryVerification -Root $fixture -Generate { param($Config,$Destination); Set-Content -LiteralPath (Join-Path $Destination 'models.go') -Value 'package stale' -Encoding utf8NoBOM } } 'different regenerated bytes'
    if((Get-Content -LiteralPath (Join-Path $output 'models.go') -Raw).Trim() -cne $original){throw 'Verification mutated the tracked generated baseline.'}
    $checks+=2
    Set-Content -LiteralPath (Join-Path $output 'orphan.go') -Value $original -Encoding utf8NoBOM
    Assert-PersistenceRejection { Invoke-GeneratedQueryVerification -Root $fixture -Generate { param($Config,$Destination); Set-Content -LiteralPath (Join-Path $Destination 'models.go') -Value $original -Encoding utf8NoBOM } } 'stale orphan output retained by an in-place generator'
    $checks++
    Assert-PersistenceRejection { Invoke-GeneratedQueryVerification -Root $fixture -Generate { throw 'generator failed' } } 'generator failure'
    $checks++
    $cache=Join-Path $fixture '.cache/generated-query-checks'
    if((Test-Path -LiteralPath $cache) -and @(Get-ChildItem -LiteralPath $cache -Force).Count){throw 'Generation verification did not clean its own temporary output.'}
    $checks++
    $context=[pscustomobject]@{State=(Join-Path $fixture '.local/dev')}
    New-Item -ItemType Directory -Path $context.State -Force | Out-Null
    $savedDatabase=[Environment]::GetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL','Process')
    $owned='postgresql://test-only@127.0.0.1:1/owned-fixture'
    try {
        [Environment]::SetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL','unrelated-caller-value','Process')
        Set-Content -LiteralPath (Join-Path $context.State 'database-url.txt') -Value $owned -Encoding utf8NoBOM
        Invoke-LocalPersistenceVerification $context {
            if([Environment]::GetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL','Process') -cne $owned){throw 'Persistence did not select its own checkout database.'}
        }
        if([Environment]::GetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL','Process') -cne 'unrelated-caller-value'){throw 'Persistence leaked its database selection.'}
        $checks+=2
        Assert-PersistenceRejection { Invoke-LocalPersistenceVerification $context { throw 'actual verification failed' } } 'failed local verification'
        if([Environment]::GetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL','Process') -cne 'unrelated-caller-value'){throw 'Failed persistence verification leaked its database selection.'}
        $checks+=2
        Set-Content -LiteralPath (Join-Path $context.State 'database-url.txt') -Value ' ' -Encoding utf8NoBOM
        Assert-PersistenceRejection { Invoke-LocalPersistenceVerification $context {} } 'blank checkout database identity'
        $checks++
        Remove-Item -LiteralPath (Join-Path $context.State 'database-url.txt')
        Assert-PersistenceRejection { Invoke-LocalPersistenceVerification $context {} } 'absent checkout database identity'
        $checks++
    } finally { [Environment]::SetEnvironmentVariable('SUITEWARD_TEST_DATABASE_URL',$savedDatabase,'Process') }
} finally {
    $resolved=[IO.Path]::GetFullPath($fixture)
    if(-not $resolved.StartsWith($base+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Refusing cleanup outside owned persistence fixture.'}
    if(Test-Path -LiteralPath $resolved){Remove-Item -LiteralPath $resolved -Recurse -Force}
}
Write-Output "Passed $checks generation freshness boundary checks. Real sqlc evidence remains separate."
